from src.main import run_prueba

def ejecutar_pruebas(variante="A", k=4):
    ESTADO = "10000000000000000000"  # 20 caracteres

    pruebas = [
        ("ABCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRST"),
        ("ABCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRS"),
        ("ABCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRST"),
        ("ABCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRS"),
        ("ABCDEFGHIJKLMNOPQRST", "ABDEGHJKMNPQST"),
        ("ABCDEFGHIJKLMNOPQRST", "ACEGIKMOQS"),
        ("ABCDEFGHIJKLMNOPQRST", "BDFHJLNPRT"),

        ("ABCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRST"),
        ("ABCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRS"),
        ("ABCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRST"),
        ("ABCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRS"),
        ("ABCDEFGHIJKLMNOPQRS", "ABDEGHJKMNPQST"),
        ("ABCDEFGHIJKLMNOPQRS", "ACEGIKMOQS"),
        ("ABCDEFGHIJKLMNOPQRS", "BDFHJLNPRT"),

        ("BCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRST"),
        ("BCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRS"),
        ("BCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRST"),
        ("BCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRS"),
        ("BCDEFGHIJKLMNOPQRST", "ABDEGHJKMNPQST"),
        ("BCDEFGHIJKLMNOPQRST", "ACEGIKMOQS"),
        ("BCDEFGHIJKLMNOPQRST", "BDFHJLNPRT"),

        ("BCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRST"),
        ("BCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRS"),
        ("BCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRST"),
        ("BCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRS"),
        ("BCDEFGHIJKLMNOPQRS", "ABDEGHJKMNPQST"),
        ("BCDEFGHIJKLMNOPQRS", "ACEGIKMOQS"),
        ("BCDEFGHIJKLMNOPQRS", "BDFHJLNPRT"),

        ("ABDEGHJKMNPQST", "ABCDEFGHIJKLMNOPQRST"),
        ("ABDEGHJKMNPQST", "ABCDEFGHIJKLMNOPQRS"),
        ("ABDEGHJKMNPQST", "BCDEFGHIJKLMNOPQRST"),
        ("ABDEGHJKMNPQST", "BCDEFGHIJKLMNOPQRS"),
        ("ABDEGHJKMNPQST", "ABDEGHJKMNPQST"),
        ("ABDEGHJKMNPQST", "ACEGIKMOQS"),
        ("ABDEGHJKMNPQST", "BDFHJLNPRT"),

        ("ACEGIKMOQS", "ABCDEFGHIJKLMNOPQRST"),
        ("ACEGIKMOQS", "ABCDEFGHIJKLMNOPQRS"),
        ("ACEGIKMOQS", "BCDEFGHIJKLMNOPQRST"),
        ("ACEGIKMOQS", "BCDEFGHIJKLMNOPQRS"),
        ("ACEGIKMOQS", "ABDEGHJKMNPQST"),
        ("ACEGIKMOQS", "ACEGIKMOQS"),
        ("ACEGIKMOQS", "BDFHJLNPRT"),

        ("BDFHJLNPRT", "ABCDEFGHIJKLMNOPQRST"),
        ("BDFHJLNPRT", "ABCDEFGHIJKLMNOPQRS"),
        ("BDFHJLNPRT", "BCDEFGHIJKLMNOPQRST"),
        ("BDFHJLNPRT", "BCDEFGHIJKLMNOPQRS"),
        ("BDFHJLNPRT", "ABDEGHJKMNPQST"),
        ("BDFHJLNPRT", "ACEGIKMOQS"),
        ("BDFHJLNPRT", "BDFHJLNPRT"),

        ("BCDEFGJKLMNO", "BCDEFGHIJKLMNO"),
    ]

    for i, (alcance, mecanismo) in enumerate(pruebas, 1):
        print(f"\n{'='*60}")
        print(f"Prueba {i}/{len(pruebas)}")
        run_prueba(alcance, mecanismo, k=k, estado_inicio=ESTADO, variante=variante)