from src.main import run_prueba

def ejecutar_pruebas(variante="A", k=4):
    ESTADO = "1000000000000000000000"  # 22 caracteres

    pruebas = [
        ("ABCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTU"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTUV"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTU"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "ABDEGHJKMNPQSTV"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "ACEGIKMOQSU"),
        ("ABCDEFGHIJKLMNOPQRSTUV", "BDFHJLNPRTV"),

        ("ABCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("ABCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTU"),
        ("ABCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTUV"),
        ("ABCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTU"),
        ("ABCDEFGHIJKLMNOPQRSTU", "ABDEGHJKMNPQSTV"),
        ("ABCDEFGHIJKLMNOPQRSTU", "ACEGIKMOQSU"),
        ("ABCDEFGHIJKLMNOPQRSTU", "BDFHJLNPRTV"),

        ("BCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("BCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTU"),
        ("BCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTUV"),
        ("BCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTU"),
        ("BCDEFGHIJKLMNOPQRSTUV", "ABDEGHJKMNPQSTV"),
        ("BCDEFGHIJKLMNOPQRSTUV", "ACEGIKMOQSU"),
        ("BCDEFGHIJKLMNOPQRSTUV", "BDFHJLNPRTV"),

        ("BCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("BCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTU"),
        ("BCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTUV"),
        ("BCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTU"),
        ("BCDEFGHIJKLMNOPQRSTU", "ABDEGHJKMNPQSTV"),
        ("BCDEFGHIJKLMNOPQRSTU", "ACEGIKMOQSU"),
        ("BCDEFGHIJKLMNOPQRSTU", "BDFHJLNPRTV"),

        ("ABDEGHJKMNPQSTV", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("ABDEGHJKMNPQSTV", "ABCDEFGHIJKLMNOPQRSTU"),
        ("ABDEGHJKMNPQSTV", "BCDEFGHIJKLMNOPQRSTUV"),
        ("ABDEGHJKMNPQSTV", "BCDEFGHIJKLMNOPQRSTU"),
        ("ABDEGHJKMNPQSTV", "ABDEGHJKMNPQSTV"),
        ("ABDEGHJKMNPQSTV", "ACEGIKMOQSU"),
        ("ABDEGHJKMNPQSTV", "BDFHJLNPRTV"),

        ("ACEGIKMOQSU", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("ACEGIKMOQSU", "ABCDEFGHIJKLMNOPQRSTU"),
        ("ACEGIKMOQSU", "BCDEFGHIJKLMNOPQRSTUV"),
        ("ACEGIKMOQSU", "BCDEFGHIJKLMNOPQRSTU"),
        ("ACEGIKMOQSU", "ABDEGHJKMNPQSTV"),
        ("ACEGIKMOQSU", "ACEGIKMOQSU"),
        ("ACEGIKMOQSU", "BDFHJLNPRTV"),

        ("BDFHJLNPRTV", "ABCDEFGHIJKLMNOPQRSTUV"),
        ("BDFHJLNPRTV", "ABCDEFGHIJKLMNOPQRSTU"),
        ("BDFHJLNPRTV", "BCDEFGHIJKLMNOPQRSTUV"),
        ("BDFHJLNPRTV", "BCDEFGHIJKLMNOPQRSTU"),
        ("BDFHJLNPRTV", "ABDEGHJKMNPQSTV"),
        ("BDFHJLNPRTV", "ACEGIKMOQSU"),
        ("BDFHJLNPRTV", "BDFHJLNPRTV"),

        ("ACDEFGHIJKLMNOPQRST", "ACDEFGHIJKLMNOPQRST"),
    ]

    for i, (alcance, mecanismo) in enumerate(pruebas, 1):
        print(f"\n{'='*60}")
        print(f"Prueba {i}/{len(pruebas)}")
        run_prueba(alcance, mecanismo, k=k, estado_inicio=ESTADO, variante=variante)