from src.main import run_prueba

# Lógica: Estado inicial de 15 nodos con el primer nodo activo (A=1, B..O=0).
#         La convención "1" + "0"*(n-1) es el estado estándar del benchmark del proyecto.
# Sintaxis: String literal de 10,15,20,22,25 caracteres — cada carácter corresponde a un nodo del sistema.
ESTADO = "1000000000000000000000"
# Lógica: k=3 configura la tri-partición exacta (GeometricSIA). Cambiar a k=4,5 activa
#         la heurística greedy de k-partición (KGeometricSIA).
# Sintaxis: Entero asignado a constante de módulo; se pasa como argumento a `run_prueba`.
K = 3
# Lógica: Letra de variante del archivo de TPM a cargar ("A" → N15A.csv, "B" → N15B.csv).
#         Cambiar aquí para seleccionar un dataset diferente sin tocar ningún otro archivo.
# Sintaxis: String de un solo carácter; se pasa como keyword argument `variante=` a `run_prueba`.
VARIANTE = "A"

# Lógica: Lista de pares (alcance, mecanismo) en notación de letras del Excel de pruebas.
#         Cubre combinaciones sistemáticas de subconjuntos de los 15 nodos para validar
#         que la estrategia produce resultados coherentes en distintos subsistemas.
# Sintaxis: Lista de tuplas `(str, str)`; se itera con desempaquetado `for i, (alcance, mecanismo)`.
# pruebas = [
#     ("ABCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRST"),
#     ("ABCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRS"),
#     ("ABCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRST"),
#     ("ABCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRS"),
#     ("ABCDEFGHIJKLMNOPQRST", "ABDEGHJKMNPQST"),
#     ("ABCDEFGHIJKLMNOPQRST", "ACEGIKMOQS"),
#     ("ABCDEFGHIJKLMNOPQRST", "BDFHJLNPRT"),

#     ("ABCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRST"),
#     ("ABCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRS"),
#     ("ABCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRST"),
#     ("ABCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRS"),
#     ("ABCDEFGHIJKLMNOPQRS", "ABDEGHJKMNPQST"),
#     ("ABCDEFGHIJKLMNOPQRS", "ACEGIKMOQS"),
#     ("ABCDEFGHIJKLMNOPQRS", "BDFHJLNPRT"),

#     ("BCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRST"),
#     ("BCDEFGHIJKLMNOPQRST", "ABCDEFGHIJKLMNOPQRS"),
#     ("BCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRST"),
#     ("BCDEFGHIJKLMNOPQRST", "BCDEFGHIJKLMNOPQRS"),
#     ("BCDEFGHIJKLMNOPQRST", "ABDEGHJKMNPQST"),
#     ("BCDEFGHIJKLMNOPQRST", "ACEGIKMOQS"),
#     ("BCDEFGHIJKLMNOPQRST", "BDFHJLNPRT"),

#     ("BCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRST"),
#     ("BCDEFGHIJKLMNOPQRS", "ABCDEFGHIJKLMNOPQRS"),
#     ("BCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRST"),
#     ("BCDEFGHIJKLMNOPQRS", "BCDEFGHIJKLMNOPQRS"),
#     ("BCDEFGHIJKLMNOPQRS", "ABDEGHJKMNPQST"),
#     ("BCDEFGHIJKLMNOPQRS", "ACEGIKMOQS"),
#     ("BCDEFGHIJKLMNOPQRS", "BDFHJLNPRT"),

#     ("ABDEGHJKMNPQST", "ABCDEFGHIJKLMNOPQRST"),
#     ("ABDEGHJKMNPQST", "ABCDEFGHIJKLMNOPQRS"),
#     ("ABDEGHJKMNPQST", "BCDEFGHIJKLMNOPQRST"),
#     ("ABDEGHJKMNPQST", "BCDEFGHIJKLMNOPQRS"),
#     ("ABDEGHJKMNPQST", "ABDEGHJKMNPQST"),
#     ("ABDEGHJKMNPQST", "ACEGIKMOQS"),
#     ("ABDEGHJKMNPQST", "BDFHJLNPRT"),

#     ("ACEGIKMOQS", "ABCDEFGHIJKLMNOPQRST"),
#     ("ACEGIKMOQS", "ABCDEFGHIJKLMNOPQRS"),
#     ("ACEGIKMOQS", "BCDEFGHIJKLMNOPQRST"),
#     ("ACEGIKMOQS", "BCDEFGHIJKLMNOPQRS"),
#     ("ACEGIKMOQS", "ABDEGHJKMNPQST"),
#     ("ACEGIKMOQS", "ACEGIKMOQS"),
#     ("ACEGIKMOQS", "BDFHJLNPRT"),

#     ("BDFHJLNPRT", "ABCDEFGHIJKLMNOPQRST"),
#     ("BDFHJLNPRT", "ABCDEFGHIJKLMNOPQRS"),
#     ("BDFHJLNPRT", "BCDEFGHIJKLMNOPQRST"),
#     ("BDFHJLNPRT", "BCDEFGHIJKLMNOPQRS"),
#     ("BDFHJLNPRT", "ABDEGHJKMNPQST"),
#     ("BDFHJLNPRT", "ACEGIKMOQS"),
#     ("BDFHJLNPRT", "BDFHJLNPRT"),

#     ("BCDEFGJKLMNO", "BCDEFGHIJKLMNO"),
# ]  


""" 
10 nodos
pruebas = [
    ("ABCDEFGHIJ", "ABCDEFGHIJ"),
    ("ABCDEFGHIJ", "ABCDEFGHI"),
    ("ABCDEFGHIJ", "BCDEFGHIJ"),
    ("ABCDEFGHIJ", "BCDEFGHI"),
    ("ABCDEFGHIJ", "ABDEGHJ"),
    ("ABCDEFGHIJ", "ACEGI"),
    ("ABCDEFGHIJ", "BDFHJ"),

    ("ABCDEFGHI", "ABCDEFGHIJ"),
    ("ABCDEFGHI", "ABCDEFGHI"),
    ("ABCDEFGHI", "BCDEFGHIJ"),
    ("ABCDEFGHI", "BCDEFGHI"),
    ("ABCDEFGHI", "ABDEGHJ"),
    ("ABCDEFGHI", "ACEGI"),
    ("ABCDEFGHI", "BDFHJ"),

    ("BCDEFGHIJ", "ABCDEFGHIJ"),
    ("BCDEFGHIJ", "ABCDEFGHI"),
    ("BCDEFGHIJ", "BCDEFGHIJ"),
    ("BCDEFGHIJ", "BCDEFGHI"),
    ("BCDEFGHIJ", "ABDEGHJ"),
    ("BCDEFGHIJ", "ACEGI"),
    ("BCDEFGHIJ", "BDFHJ"),

    ("BCDEFGHI", "ABCDEFGHIJ"),
    ("BCDEFGHI", "ABCDEFGHI"),
    ("BCDEFGHI", "BCDEFGHIJ"),
    ("BCDEFGHI", "BCDEFGHI"),
    ("BCDEFGHI", "ABDEGHJ"),
    ("BCDEFGHI", "ACEGI"),
    ("BCDEFGHI", "BDFHJ"),

    ("ABDEGHJ", "ABCDEFGHIJ"),
    ("ABDEGHJ", "ABCDEFGHI"),
    ("ABDEGHJ", "BCDEFGHIJ"),
    ("ABDEGHJ", "BCDEFGHI"),
    ("ABDEGHJ", "ABDEGHJ"),
    ("ABDEGHJ", "ACEGI"),
    ("ABDEGHJ", "BDFHJ"),

    ("ACEGI", "ABCDEFGHIJ"),
    ("ACEGI", "ABCDEFGHI"),
    ("ACEGI", "BCDEFGHIJ"),
    ("ACEGI", "BCDEFGHI"),
    ("ACEGI", "ABDEGHJ"),
    ("ACEGI", "ACEGI"),
    ("ACEGI", "BDFHJ"),

    ("BDFHJ", "ABCDEFGHIJ"),
    ("BDFHJ", "ABCDEFGHI"),
    ("BDFHJ", "BCDEFGHIJ"),
    ("BDFHJ", "BCDEFGHI"),
    ("BDFHJ", "ABDEGHJ"),
    ("BDFHJ", "ACEGI"),
    ("BDFHJ", "BDFHJ"),
] """

""" pruebas = [
    ("ABCDEFGHIJKLMNO", "ABCDEFGHIJKLMNO"),
    ("ABCDEFGHIJKLMNO", "ABCDEFGHIJKLMN"),
    ("ABCDEFGHIJKLMNO", "BCDEFGHIJKLMNO"),
    ("ABCDEFGHIJKLMNO", "BCDEFGHIJKLMN"),
    ("ABCDEFGHIJKLMNO", "ABDEGHJKMN"),
    ("ABCDEFGHIJKLMNO", "ACEGIKMO"),
    ("ABCDEFGHIJKLMNO", "BDFHJLN"),

    ("ABCDEFGHIJKLMN", "ABCDEFGHIJKLMNO"),
    ("ABCDEFGHIJKLMN", "ABCDEFGHIJKLMN"),
    ("ABCDEFGHIJKLMN", "BCDEFGHIJKLMNO"),
    ("ABCDEFGHIJKLMN", "BCDEFGHIJKLMN"),
    ("ABCDEFGHIJKLMN", "ABDEGHJKMN"),
    ("ABCDEFGHIJKLMN", "ACEGIKMO"),
    ("ABCDEFGHIJKLMN", "BDFHJLN"),

    ("BCDEFGHIJKLMNO", "ABCDEFGHIJKLMNO"),
    ("BCDEFGHIJKLMNO", "ABCDEFGHIJKLMN"),
    ("BCDEFGHIJKLMNO", "BCDEFGHIJKLMNO"),
    ("BCDEFGHIJKLMNO", "BCDEFGHIJKLMN"),
    ("BCDEFGHIJKLMNO", "ABDEGHJKMN"),
    ("BCDEFGHIJKLMNO", "ACEGIKMO"),
    ("BCDEFGHIJKLMNO", "BDFHJLN"),

    ("BCDEFGHIJKLMN", "ABCDEFGHIJKLMNO"),
    ("BCDEFGHIJKLMN", "ABCDEFGHIJKLMN"),
    ("BCDEFGHIJKLMN", "BCDEFGHIJKLMNO"),
    ("BCDEFGHIJKLMN", "BCDEFGHIJKLMN"),
    ("BCDEFGHIJKLMN", "ABDEGHJKMN"),
    ("BCDEFGHIJKLMN", "ACEGIKMO"),
    ("BCDEFGHIJKLMN", "BDFHJLN"),

    ("ABDEGHJKMN", "ABCDEFGHIJKLMNO"),
    ("ABDEGHJKMN", "ABCDEFGHIJKLMN"),
    ("ABDEGHJKMN", "BCDEFGHIJKLMNO"),
    ("ABDEGHJKMN", "BCDEFGHIJKLMN"),
    ("ABDEGHJKMN", "ABDEGHJKMN"),
    ("ABDEGHJKMN", "ACEGIKMO"),
    ("ABDEGHJKMN", "BDFHJLN"),

    ("ACEGIKMO", "ABCDEFGHIJKLMNO"),
    ("ACEGIKMO", "ABCDEFGHIJKLMN"),
    ("ACEGIKMO", "BCDEFGHIJKLMNO"),
    ("ACEGIKMO", "BCDEFGHIJKLMN"),
    ("ACEGIKMO", "ABDEGHJKMN"),
    ("ACEGIKMO", "ACEGIKMO"),
    ("ACEGIKMO", "BDFHJLN"),

    ("BDFHJLN", "ABCDEFGHIJKLMNO"),
    ("BDFHJLN", "ABCDEFGHIJKLMN"),
    ("BDFHJLN", "BCDEFGHIJKLMNO"),
    ("BDFHJLN", "BCDEFGHIJKLMN"),
    ("BDFHJLN", "ABDEGHJKMN"),
    ("BDFHJLN", "ACEGIKMO"),
    ("BDFHJLN", "BDFHJLN"),

    ("BCDEFGJKLMNO", "BCDEFGHIJKLMNO"),
] """

pruebas = [
    ("ABCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTU"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTUV"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTU"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "ABDEGHJKMNPQSTV"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "ACEGIKMOQSU"),
    ("ABCDEFGHIJKLMNOPQRSTUV", "BDFHJLNPRTV"),

    ("ABCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("ABCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTU"),
    ("ABCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTUV"),
    ("ABCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTU"),
    ("ABCDEFGHIJKLMNOPQRSTU", "ABDEGHJKMNPQSTV"),
    ("ABCDEFGHIJKLMNOPQRSTU", "ACEGIKMOQSU"),
    ("ABCDEFGHIJKLMNOPQRSTU", "BDFHJLNPRTV"),

    ("BCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("BCDEFGHIJKLMNOPQRSTUV", "ABCDEFGHIJKLMNOPQRSTU"),
    ("BCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTUV"),
    ("BCDEFGHIJKLMNOPQRSTUV", "BCDEFGHIJKLMNOPQRSTU"),
    ("BCDEFGHIJKLMNOPQRSTUV", "ABDEGHJKMNPQSTV"),
    ("BCDEFGHIJKLMNOPQRSTUV", "ACEGIKMOQSU"),
    ("BCDEFGHIJKLMNOPQRSTUV", "BDFHJLNPRTV"),

    ("BCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("BCDEFGHIJKLMNOPQRSTU", "ABCDEFGHIJKLMNOPQRSTU"),
    ("BCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTUV"),
    ("BCDEFGHIJKLMNOPQRSTU", "BCDEFGHIJKLMNOPQRSTU"),
    ("BCDEFGHIJKLMNOPQRSTU", "ABDEGHJKMNPQSTV"),
    ("BCDEFGHIJKLMNOPQRSTU", "ACEGIKMOQSU"),
    ("BCDEFGHIJKLMNOPQRSTU", "BDFHJLNPRTV"),

    ("ABDEGHJKMNPQSTV", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("ABDEGHJKMNPQSTV", "ABCDEFGHIJKLMNOPQRSTU"),
    ("ABDEGHJKMNPQSTV", "BCDEFGHIJKLMNOPQRSTUV"),
    ("ABDEGHJKMNPQSTV", "BCDEFGHIJKLMNOPQRSTU"),
    ("ABDEGHJKMNPQSTV", "ABDEGHJKMNPQSTV"),
    ("ABDEGHJKMNPQSTV", "ACEGIKMOQSU"),
    ("ABDEGHJKMNPQSTV", "BDFHJLNPRTV"),

    ("ACEGIKMOQSU", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("ACEGIKMOQSU", "ABCDEFGHIJKLMNOPQRSTU"),
    ("ACEGIKMOQSU", "BCDEFGHIJKLMNOPQRSTUV"),
    ("ACEGIKMOQSU", "BCDEFGHIJKLMNOPQRSTU"),
    ("ACEGIKMOQSU", "ABDEGHJKMNPQSTV"),
    ("ACEGIKMOQSU", "ACEGIKMOQSU"),
    ("ACEGIKMOQSU", "BDFHJLNPRTV"),

    ("BDFHJLNPRTV", "ABCDEFGHIJKLMNOPQRSTUV"),
    ("BDFHJLNPRTV", "ABCDEFGHIJKLMNOPQRSTU"),
    ("BDFHJLNPRTV", "BCDEFGHIJKLMNOPQRSTUV"),
    ("BDFHJLNPRTV", "BCDEFGHIJKLMNOPQRSTU"),
    ("BDFHJLNPRTV", "ABDEGHJKMNPQSTV"),
    ("BDFHJLNPRTV", "ACEGIKMOQSU"),
    ("BDFHJLNPRTV", "BDFHJLNPRTV"),

    ("ACDEFGHIJKLMNOPQRST", "ACDEFGHIJKLMNOPQRST"),
]

# pruebas = [
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "ABDEGHJKMNPQSTVWY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "ACEGIKMOQSUWY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWXY", "BDFHJLNPRTVX"),

#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "ABDEGHJKMNPQSTVWY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "ACEGIKMOQSUWY"),
#     ("ABCDEFGHIJKLMNOPQRSTUVWX", "BDFHJLNPRTVX"),

#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "ABDEGHJKMNPQSTVWY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "ACEGIKMOQSUWY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWXY", "BDFHJLNPRTVX"),

#     ("BCDEFGHIJKLMNOPQRSTUVWX", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "ABDEGHJKMNPQSTVWY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "ACEGIKMOQSUWY"),
#     ("BCDEFGHIJKLMNOPQRSTUVWX", "BDFHJLNPRTVX"),

#     ("ABDEGHJKMNPQSTVWY", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABDEGHJKMNPQSTVWY", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABDEGHJKMNPQSTVWY", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ABDEGHJKMNPQSTVWY", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ABDEGHJKMNPQSTVWY", "ABDEGHJKMNPQSTVWY"),
#     ("ABDEGHJKMNPQSTVWY", "ACEGIKMOQSUWY"),
#     ("ABDEGHJKMNPQSTVWY", "BDFHJLNPRTVX"),

#     ("ACEGIKMOQSUWY", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ACEGIKMOQSUWY", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ACEGIKMOQSUWY", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("ACEGIKMOQSUWY", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("ACEGIKMOQSUWY", "ABDEGHJKMNPQSTVWY"),
#     ("ACEGIKMOQSUWY", "ACEGIKMOQSUWY"),
#     ("ACEGIKMOQSUWY", "BDFHJLNPRTVX"),

#     ("BDFHJLNPRTVX", "ABCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BDFHJLNPRTVX", "ABCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BDFHJLNPRTVX", "BCDEFGHIJKLMNOPQRSTUVWXY"),
#     ("BDFHJLNPRTVX", "BCDEFGHIJKLMNOPQRSTUVWX"),
#     ("BDFHJLNPRTVX", "ABDEGHJKMNPQSTVWY"),
#     ("BDFHJLNPRTVX", "ACEGIKMOQSUWY"),
#     ("BDFHJLNPRTVX", "BDFHJLNPRTVX"),

#     ("ACDEFGHIJKLMNOPQRSTVX", "ACDEFGHIJKLMNOPQRSTVX"),
# ]

# Lógica: Itera la lista de pruebas ejecutando `run_prueba` para cada par (alcance, mecanismo)
#         con el estado inicial y k configurados globalmente; imprime un encabezado por prueba
#         para facilitar la lectura de la salida en consola o en el archivo de log (tee salida.txt).
# Sintaxis: `enumerate(iterable, 1)` produce pares (1, item), (2, item), ... para indexar desde 1.
for i, (alcance, mecanismo) in enumerate(pruebas, 1):
    print(f"\n{'='*60}")
    #print(f"Prueba {i}/{len(pruebas)}")
    print(f"Prueba {i}/50")
    run_prueba(alcance, mecanismo, k=K, estado_inicio=ESTADO, variante=VARIANTE)


# python run_10A_k.py | tee salida.txt